import { Package, Plus } from 'lucide-react';
import styles from './Estoque.module.scss';

const produtos = [
  // Perfumes 100ml
  {
    id: '100',
    codigo: '100',
    nome: 'Perfume SOXERO 100ml masculino',
    descricao: 'Fragrância masculina SOXERO',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 1100,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 45.0,
  },
  {
    id: '105',
    codigo: '105',
    nome: 'Perfume SOXERO 100ml feminino',
    descricao: 'Fragrância feminina SOXERO',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1155,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 46.2,
  },
  {
    id: '110',
    codigo: '110',
    nome: 'Perfume SOHODOR 100ml masculino',
    descricao: 'Fragrância masculina SOHODOR',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 1210,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 47.4,
  },
  {
    id: '115',
    codigo: '115',
    nome: 'Perfume SOHODOR 100ml feminino',
    descricao: 'Fragrância feminina SOHODOR',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 0,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 48.6,
  },
  {
    id: '120',
    codigo: '120',
    nome: 'Perfume SOLAVANDO 100ml masculino',
    descricao: 'Fragrância masculina SOLAVANDO',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 1320,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 49.8,
  },
  {
    id: '125',
    codigo: '125',
    nome: 'Perfume SOLAVANDO 100ml feminino',
    descricao: 'Fragrância feminina SOLAVANDO',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1375,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 51.0,
  },
  {
    id: '130',
    codigo: '130',
    nome: 'Perfume SONAREZA 100ml masculino',
    descricao: 'Fragrância masculina SONAREZA',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 1430,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 52.2,
  },
  {
    id: '135',
    codigo: '135',
    nome: 'Perfume SONAREZA 100ml feminino',
    descricao: 'Fragrância feminina SONAREZA',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1485,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 53.4,
  },
  {
    id: '140',
    codigo: '140',
    nome: 'Perfume SONOAR 100ml masculino',
    descricao: 'Fragrância masculina SONOAR',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 0,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 54.6,
  },
  {
    id: '145',
    codigo: '145',
    nome: 'Perfume SONOAR 100ml feminino',
    descricao: 'Fragrância feminina SONOAR',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1595,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 55.8,
  },
  {
    id: '150',
    codigo: '150',
    nome: 'Perfume SOFRENCIA 100ml masculino',
    descricao: 'Fragrância masculina SOFRENCIA',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 1650,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 57.0,
  },
  {
    id: '155',
    codigo: '155',
    nome: 'Perfume SOFRENCIA 100ml feminino',
    descricao: 'Fragrância feminina SOFRENCIA',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1705,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 58.2,
  },
  {
    id: '160',
    codigo: '160',
    nome: 'Perfume SOSENTE 100ml masculino',
    descricao: 'Fragrância masculina SOSENTE',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 1760,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 59.4,
  },
  {
    id: '165',
    codigo: '165',
    nome: 'Perfume SOSENTE 100ml feminino',
    descricao: 'Fragrância feminina SOSENTE',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1815,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 60.6,
  },
  {
    id: '170',
    codigo: '170',
    nome: 'Perfume SOREZANDO 100ml masculino',
    descricao: 'Fragrância masculina SOREZANDO',
    categoriaId: '1',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 800,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 61.8,
  },
  {
    id: '175',
    codigo: '175',
    nome: 'Perfume SOREZANDO 100ml feminino',
    descricao: 'Fragrância feminina SOREZANDO',
    categoriaId: '1',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1925,
    estoqueMinimo: 500,
    estoqueMaximo: 2000,
    estoqueSeguranca: 600,
    pontoReposicao: 700,
    loteEconomico: 500,
    custoUnitario: 63.0,
  },

  // Perfumes 50ml
  {
    id: '200',
    codigo: '200',
    nome: 'Perfume SOXERO 50ml masculino',
    descricao: 'Fragrância masculina SOXERO',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2200,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 64.2,
  },
  {
    id: '205',
    codigo: '205',
    nome: 'Perfume SOXERO 50ml feminino',
    descricao: 'Fragrância feminina SOXERO',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 2255,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 65.4,
  },
  {
    id: '210',
    codigo: '210',
    nome: 'Perfume SOHODOR 50ml masculino',
    descricao: 'Fragrância masculina SOHODOR',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2310,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 66.6,
  },
  {
    id: '215',
    codigo: '215',
    nome: 'Perfume SOHODOR 50ml feminino',
    descricao: 'Fragrância feminina SOHODOR',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 2365,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 67.8,
  },
  {
    id: '220',
    codigo: '220',
    nome: 'Perfume SOLAVANDO 50ml masculino',
    descricao: 'Fragrância masculina SOLAVANDO',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2420,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 69.0,
  },
  {
    id: '225',
    codigo: '225',
    nome: 'Perfume SOLAVANDO 50ml feminino',
    descricao: 'Fragrância feminina SOLAVANDO',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 900,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 70.2,
  },
  {
    id: '230',
    codigo: '230',
    nome: 'Perfume SONAREZA 50ml masculino',
    descricao: 'Fragrância masculina SONAREZA',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2530,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 71.4,
  },
  {
    id: '235',
    codigo: '235',
    nome: 'Perfume SONAREZA 50ml feminino',
    descricao: 'Fragrância feminina SONAREZA',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 2585,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 72.6,
  },
  {
    id: '240',
    codigo: '240',
    nome: 'Perfume SONOAR 50ml masculino',
    descricao: 'Fragrância masculina SONOAR',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2640,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 73.8,
  },
  {
    id: '245',
    codigo: '245',
    nome: 'Perfume SONOAR 50ml feminino',
    descricao: 'Fragrância feminina SONOAR',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 0,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 75.0,
  },
  {
    id: '250',
    codigo: '250',
    nome: 'Perfume SOFRENCIA 50ml masculino',
    descricao: 'Fragrância masculina SOFRENCIA',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2750,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 76.2,
  },
  {
    id: '255',
    codigo: '255',
    nome: 'Perfume SOFRENCIA 50ml feminino',
    descricao: 'Fragrância feminina SOFRENCIA',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 2805,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 77.4,
  },
  {
    id: '260',
    codigo: '260',
    nome: 'Perfume SOSENTE 50ml masculino',
    descricao: 'Fragrância masculina SOSENTE',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2860,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 78.6,
  },
  {
    id: '265',
    codigo: '265',
    nome: 'Perfume SOSENTE 50ml feminino',
    descricao: 'Fragrância feminina SOSENTE',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 2915,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 79.8,
  },
  {
    id: '270',
    codigo: '270',
    nome: 'Perfume SOREZANDO 50ml masculino',
    descricao: 'Fragrância masculina SOREZANDO',
    categoriaId: '2',
    fornecedorId: 'FM001',
    unidade: 'UN',
    estoqueAtual: 2970,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 81.0,
  },
  {
    id: '275',
    codigo: '275',
    nome: 'Perfume SOREZANDO 50ml feminino',
    descricao: 'Fragrância feminina SOREZANDO',
    categoriaId: '2',
    fornecedorId: 'FF001',
    unidade: 'UN',
    estoqueAtual: 1200,
    estoqueMinimo: 800,
    estoqueMaximo: 3000,
    estoqueSeguranca: 1000,
    pontoReposicao: 1200,
    loteEconomico: 800,
    custoUnitario: 82.2,
  },
];

export default function Estoque() {
  return (
    <>
      <section className={styles.header}>
        <div>
          <h1>Operações de Estoque</h1>
          <p>Gerencie ajustes de estoque</p>
        </div>
        <button>
          <Plus size={18} />
          Ajuste
        </button>
      </section>
      <section className={styles.table_container}>
        <h2>Saldo Atual por Produto</h2>
        <table className={styles.table}>
          <thead>
            <tr>
              <th className="pseudo-title">Imagem</th>
              <th className="pseudo-title">Código</th>
              <th className="pseudo-title">Produto</th>
              <th className="pseudo-title">Estoque Atual</th>
              <th className="pseudo-title">Estoque Mínimo</th>
              <th className="pseudo-title">Status</th>
              <th className="pseudo-title">Valor Total</th>
            </tr>
          </thead>

          <tbody>
            {produtos.map((produto) => {
              return (
                <tr key={produto.codigo}>
                  <td>
                    <div className={styles.img}>
                      <Package />
                    </div>
                  </td>
                  <td>{produto.codigo}</td>
                  <td>{produto.nome}</td>
                  <td>{produto.estoqueAtual} un</td>
                  <td>{produto.estoqueMinimo} un</td>
                  <td>
                    <span
                      className={
                        produto.estoqueAtual === 0
                          ? styles.ruptura
                          : produto.estoqueAtual <= produto.estoqueMinimo
                            ? styles.baixo
                            : produto.estoqueAtual <= produto.pontoReposicao
                              ? styles.atencao
                              : styles.normal
                      }
                    ></span>
                  </td>
                  <td>
                    {(
                      produto.estoqueAtual * produto.custoUnitario
                    ).toLocaleString('pt-BR', {
                      style: 'currency',
                      currency: 'BRL',
                    })}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </section>
    </>
  );
}
